spring:
  application:
    name: api-ms-loans
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:oracleuser/oraclepassword@//localhost:1521/XEPDB1}
    username: ${DB_USERNAME:oracleuser}
    password: ${DB_PASSWORD:oraclepassword}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_MODE:update}
    show-sql: ${DB_LOGGIN_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

# Configuración base de OpenAPI
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  packages-to-scan: com.github.maximovj.msapiloans
  paths-to-match: /api/**

server:
  port: ${PORT:8007}