spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
  
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_MODE:validate}  # Nunca update en producción
    show-sql: ${DB_LOGGIN_SQL:false}

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    enabled: false  # Deshabilitado en producción
  api-docs:
    enabled: false  # Deshabilitado en producción

logging:
  level:
    root: WARN
    com.github.maximovj: INFO