spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:oracleuser/oraclepassword@//localhost:1521/XEPDB1?defaultRowPrefetch=100&defaultFetchSize=50}
    username: ${DB_USERNAME:oracleuser}
    password: ${DB_PASSWORD:oraclepassword}
  
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_MODE:create-drop}
    show-sql: ${DB_LOGGIN_SQL:true}

server:
  port: ${PORT:8008}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  # Configuraciones para testing
  cache:
    disabled: true
    
logging:
  level:
    org.springframework: INFO